FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN ["uv", "sync"]

COPY src ./src

# FastAPI Port
EXPOSE 8000

# Move dir for uvicorn
WORKDIR /app/src

# Create model
RUN ["uv", "run", "python", "model.py"]

# Run FastAPI backend
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]